version: '2.1'

volumes:
    kerberosagent_recordings:
    kerberosagent_snapshots:
    kerberosagent_config:

services:

    # https://github.com/kerberos/agent
    agent:
        # image: bh.cr/kerberos_io/agent
        build: ./agent
        ports:
            - "80:80"
        tty: true
        restart: always
        volumes:
            - 'kerberosagent_recordings:/home/agent/data/recordings:rw'
            - 'kerberosagent_snapshots:/home/agent/data/snapshots:rw'
            - 'kerberosagent_config:/home/agent/data/config:rw'

    # https://github.com/balenablocks/hostname
    hostname:
        image: balenablocks/hostname:latest
        restart: no
        labels:
            io.balena.features.supervisor-api: 1
        environment:
            SET_HOSTNAME: videosurveillance
    # rtsp:
    #     image: mpromonet/v4l2rtspserver
    #     restart: no
    #     ports:
    #         - "8554:8554"
    #     devices:
    #         - "/dev/video0:/dev/video0"        
    # streamer:
    #     build: ./streamer
    #     restart: always
    #     privileged: true
        # ports:
            # - "554:554"
    rtsp-simple-server:
        build: ./rtsp-simple-server
        restart: always
        privileged: true
        # ports:
        #     - "554:554"
        #     - "8554:8554"

    warp-test:
        build: ./warp-test
    # rtsp-simple-server:
    #     # image: bluenviron/mediamtx:latest-rpi
    #     image: kerberos/rtsp-simple-server:latest-rpi
    #     privileged: true
    #     restart: no
    #     network_mode: bridge
    #     devices:
    #         - "/dev/video0:/dev/video0"
    #         # - ""
    #     # volumes:
    #         - '/run/udev:/run/udev'
    #         # - '/dev:/dev:ro'
    #         - './rtsp-simple-server:/rtsp-simple-server.yml:rw'
    #     environment:
    #         # MTX_PATHS_CAM_SOURCE: rpiCamera
    #         UDEV: on
    #     tmpfs:
    #         - '/dev/shm:rw'
    #     labels:
    #         io.balena.features.kernel-modules: '1'
    # mediamtx:
    #     image: bluenviron/mediamtx:latest-rpi
    #     privileged: true
    #     restart: always
    #     network_mode: host
    #     volumes:
    #         - '/run/udev:/run/udev:ro'
    #         # - '${PWD}/mediamtx.yml:mediamtx.yml:rw'
    #     environment:
    #         MTX_PATHS_CAM_SOURCE: rpiCamera
    #     tmpfs:
    #         - '/dev/shm:exec'
    #     labels:
    #         io.balena.features.kernel-modules: '1'

