version: '2.1'

volumes:
    kerberosagent_recordings:
    kerberosagent_snapshots:
    kerberosagent_config:

services:

    # https://hub.docker.com/r/kerberos/agent
    agent:
        image: kerberos/agent:3ce9adc
        network_mode: host
        tty: true
        restart: always
        volumes:
            - 'kerberosagent_recordings:/home/agent/data/recordings:rw'
            - 'kerberosagent_snapshots:/home/agent/data/snapshots:rw'
            - 'kerberosagent_config:/home/agent/data/config:rw'

    # https://github.com/aler9/rtsp-simple-server
    rtsp-simple-server:
        image: aler9/rtsp-simple-server:latest
        network_mode: host
        privileged: true
        tmpfs: /dev/shm:exec
        restart: always
        labels:
            io.balena.features.kernel-modules: '1'
            io.balena.features.firmware: '1'
            io.balena.features.dbus: '1'
            io.balena.features.supervisor-api: '1'
            io.balena.features.resin-api: '1'
            io.balena.features.balena-socket: '1'
        environment:
            RTSP_PATHS_CAMRPI_SOURCE: 'rpiCamera'
            RTSP_PATHS_CAMUSB_RUN_ON_INIT: 'ffmpeg -f v4l2 -i /dev/video0 -pix_fmt yuv420p -preset ultrafast -b:v 600k -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH'
            RTSP_PATHS_CAMUSB_RUN_ON_INIT_RESTART: 'yes'


    # https://github.com/balenablocks/hostname
    hostname:
        image: balenablocks/hostname:latest
        restart: no
        labels:
            io.balena.features.supervisor-api: 1
        environment:
            SET_HOSTNAME: kerberos-agent
