version: '2.1'

volumes:
    kerberosagent_recordings:
    kerberosagent_snapshots:
    kerberosagent_config:

services:

    # https://github.com/kerberos/agent
    agent:
        image: bh.cr/kerberos_io/agent
        network_mode: host
        tty: true
        restart: always
        volumes:
            - 'kerberosagent_recordings:/home/agent/data/recordings:rw'
            - 'kerberosagent_snapshots:/home/agent/data/snapshots:rw'
            - 'kerberosagent_config:/home/agent/data/config:rw'

    # https://github.com/balenablocks/hostname
    hostname:
        image: balenablocks/hostname:latest
        restart: no
        labels:
            io.balena.features.supervisor-api: 1
        environment:
            SET_HOSTNAME: videosurveillance
