name: balena

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fleet: [kerberos_io/agent]

    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@v0.13.1
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          environment: balena-cloud.com
          fleet: ${{ matrix.fleet }}
          versionbot: false
          create_tag: true
